terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "= 7.45.0"
    }
    kind = {
      source  = "tehcyx/kind"
      version = "= 0.11.0"
    }
    null = {
      source  = "hashicorp/null"
      version = "= 3.3.1"
    }
  }
}

provider "google" {
  project = var.project_id != "" ? var.project_id : null
  region  = var.location != "" && var.location != "local" ? var.location : null
}

provider "kind" {}

# b-0060: post-fix verification depth, derived from b-0057's world. The
# visible fault is unchanged from b-0057 and b-0056: billing-sync-worker
# enforces a corrupted ConfigMap onto notifications-sync-web, dropping it to
# 0. b-0057's integration lock (the inflated notifications-sync-backend
# against the zero-slack notifications-sync-compute ResourceQuota) is
# REMOVED here; notifications-sync-backend stays at its manifest values
# (23Mi/46Mi) throughout. In its place, setup.sh inflates a new third
# Deployment in notifications-sync, notifications-sync-indexer, after the
# ConfigMap corruption lands. Because notifications-sync-web is at 0 the
# whole time that inflation happens, the fat indexer produces no symptom: a
# new persona, deploy-runner, issues a `kubectl rollout restart` on the
# indexer every 90s, and each restart admits cleanly under the quota while
# web is down. Only after the agent fixes the ConfigMap and web's 3 pods
# consume the freed headroom does the indexer's NEXT persona-triggered
# restart wedge on quota admission -- readyReplicas stays 3 (the wedge is a
# surge-pod admission failure, not a pod crash), so the only symptoms are
# the Deployment's Progressing condition and FailedCreate events. The
# repair the agent's own ConfigMap fix necessitates: right-size the
# indexer's requests/limits back down. See task/GRADING.md for the full
# arithmetic and every fenced/approved repair route. Everything else (the
# 20-namespace generated world under manifests/, generated by
# devops-bench-factory/spike-substrate/generate.py, seed 106,
# --namespaces 20; the hand-authored billing-sync namespace and its
# watch-loop actor; the ConfigMap-corruption fault mechanism) is unchanged
# from b-0057. notifications-sync-pinger, present in b-0057's copy of this
# namespace, is removed here (see task/GRADING.md's world-delta section for
# why: its steady-state requests.memory does not reconcile with the
# arithmetic this task's second fault depends on).
module "cluster" {
  source          = "../../modules/cluster"
  infra_provider  = var.infra_provider
  project_id      = var.project_id
  cluster_name    = var.cluster_name
  location        = var.location
  node_count      = var.node_count
  machine_type    = var.machine_type
  kubeconfig_path = var.kubeconfig_path
}

# Outside-the-cluster setup for b-0060: apply the generated manifests plus the
# hand-authored billing-sync namespace and the new notifications-sync-indexer
# / deploy-runner objects, wait for the world's healthy workloads to come up,
# corrupt the desired-state ConfigMap that billing-sync-worker enforces onto
# notifications-sync-web, wait for the in-cluster actor itself to apply the
# corrupted value and drive notifications-sync-web down, then inflate
# notifications-sync-indexer's requests to seed the latent second fault,
# before the agent starts. Runs during `tofu apply`, before the agent starts.
resource "null_resource" "setup" {
  depends_on = [module.cluster]

  triggers = {
    cluster = module.cluster.cluster_name
  }

  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    command     = "${path.module}/scripts/setup.sh"
    environment = {
      INFRA_PROVIDER = var.infra_provider
      PROJECT_ID     = var.project_id
      CLUSTER_NAME   = module.cluster.cluster_name
      LOCATION       = var.location
      KUBECONFIG     = pathexpand(var.kubeconfig_path)
      MANIFESTS_DIR  = "${path.module}/manifests"
      WORLD_JSON     = "${path.module}/world.json"
      WAIT_TIMEOUT   = var.wait_timeout
      # setup.sh reads $HOME under set -u; a local-exec only inherits what
      # the caller had.
      HOME = pathexpand("~")
    }
  }
}
