terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "= 7.45.0"
    }
    kind = {
      source  = "tehcyx/kind"
      version = "= 0.11.0"
    }
    null = {
      source  = "hashicorp/null"
      version = "= 3.3.1"
    }
  }
}

provider "google" {
  project = var.project_id != "" ? var.project_id : null
  region  = var.location != "" && var.location != "local" ? var.location : null
}

provider "kind" {}

# b-0061 (variant_of b-0059): variant_of b-0056 (adds the NetworkPolicy integration
# lock; sibling of b-0057's quota lock). The 20-namespace world under manifests/
# was generated by devops-bench-factory/spike-substrate/generate.py (seed 106,
# --namespaces 20), not hand-authored; each manifests/<namespace>.yaml file is
# self-contained (a Namespace object plus that namespace's workloads) and is
# applied directly, matching the generator's own established apply pattern and
# b-0053's stack layout. One extra namespace, billing-sync, is hand-authored
# and added to manifests/ alongside the generated 20: it runs the reverting
# actor for the first (unchanged, b-0056) fault, OUTSIDE the fault namespace
# (notifications-sync) rather than inside it. setup.sh applies every manifest,
# waits for the world's intentionally-healthy workloads to reach Ready (driven from
# world.json, not a hardcoded list), then corrupts billing-sync-config's ConfigMap
# (the desired-state ConfigMap billing-sync-worker's Deployment watches and enforces
# onto notifications-sync-web) and waits, bounded, until the in-cluster actor has
# actually applied the corrupted value and the symptom is observable. New in b-0059:
# disable_default_cni installs Calico (a real NetworkPolicy-enforcing CNI) in place
# of kindnet, and setup.sh's phase 2 corrupts one allow-rule's namespaceSelector
# value in notifications-sync, cutting search-api's path to notifications-sync-web
# independently of the ConfigMap fault. See task/GRADING.md for the full design,
# seed selection rationale, the NetworkPolicy lock's arithmetic, and the manifest
# post-processing fixups applied after generation.
module "cluster" {
  source              = "../../modules/cluster"
  infra_provider      = var.infra_provider
  project_id          = var.project_id
  cluster_name        = var.cluster_name
  location            = var.location
  node_count          = var.node_count
  machine_type        = var.machine_type
  kubeconfig_path     = var.kubeconfig_path
  disable_default_cni = true
}

# Outside-the-cluster setup for b-0061 (variant_of b-0059): apply the generated
# manifests plus the hand-authored billing-sync namespace and the boot-time
# NetworkPolicy furniture in notifications-sync, wait for the world's healthy
# workloads to come up, corrupt the desired-state ConfigMap that billing-sync-worker
# enforces onto notifications-sync-web, wait for the in-cluster actor itself to
# apply the corrupted value and drive notifications-sync-web down, then run phase
# 2: corrupt allow-from-search-api's namespaceSelector value, before the agent
# starts. Runs during `tofu apply`, after the cluster module has already installed
# Calico and waited for it (module "cluster" above), before the agent starts.
resource "null_resource" "setup" {
  depends_on = [module.cluster]

  triggers = {
    cluster = module.cluster.cluster_name
  }

  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    command     = "${path.module}/scripts/setup.sh"
    environment = {
      INFRA_PROVIDER = var.infra_provider
      PROJECT_ID     = var.project_id
      CLUSTER_NAME   = module.cluster.cluster_name
      LOCATION       = var.location
      KUBECONFIG     = pathexpand(var.kubeconfig_path)
      MANIFESTS_DIR  = "${path.module}/manifests"
      WORLD_JSON     = "${path.module}/world.json"
      WAIT_TIMEOUT   = var.wait_timeout
      # setup.sh reads $HOME under set -u; a local-exec only inherits what
      # the caller had.
      HOME = pathexpand("~")
    }
  }
}
